export const Products = [
  {
    id: 1,
    size: "500 ml ",
    color: "white ",
    name: "Earthen Bottle",
    quantityPrice: 48,
    price: 48,
    imageSrc: "/bottles.jpg",
    imageAlt:
      "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
    quantity: 1,
  },
  {
    id: 2,
    size: "1000ml ",
    color: "pink ",
    name: "Nomad Tumbler",
    quantityPrice: 30,
    price: 30,
    imageSrc: "/water-bottle.jpg",
    imageAlt:
      "Olive drab green insulated bottle with flared screw lid and flat top.",
    quantity: 1,
  },
  {
    id: 3,
    size: "Medium",
    color: "Black",
    name: "Hat",
    quantityPrice: 89,
    price: 89,
    imageSrc: "/hat.png",
    imageAlt: "Hat",
    quantity: 1,
  },
  {
    id: 4,
    size: "Long",
    color: "Black ",
    name: "Pencil",
    quantityPrice: 10,
    price: 10,
    imageSrc: "/pencils.jpg",
    imageAlt:
      "Hand holding black machined steel mechanical pencil with brass tip and top.",
    quantity: 1,
  },
  {
    id: 5,
    size: "--",
    color: "Black ",
    name: "Alaram Clock",
    quantityPrice: 60,
    price: 60,
    imageSrc: "/alaram-clock.jpg",
    imageAlt:
      "Hand holding black machined steel mechanical pencil with brass tip and top.",
    quantity: 1,
  },
  {
    id: 6,
    size: "--",
    color: " Black",
    name: "Ball Pen ",
    quantityPrice: 6,
    price: 6,
    imageSrc: "/Ball-pen.png",
    imageAlt: "Ball pen",
    quantity: 1,
  },
  {
    id: 7,
    size: "Large",
    color: "Black",
    name: "Black Cap ",
    quantityPrice: 40,
    price: 40,
    imageSrc: "/black-cap.png",
    imageAlt: "Black cap",
    quantity: 1,
  },
  {
    id: 8,
    size: "Novel ",
    color: "Vintage",
    name: "Book",
    quantityPrice: 30,
    price: 30,
    imageSrc: "/book.jpg",
    imageAlt: "Book",
    quantity: 1,
  },
  {
    id: 9,
    size: "Long ",
    color: "Black ",
    name: "Calligraphy Pen ",
    quantityPrice: 15,
    price: 15,
    imageSrc: "/Calligraphy-pen.jpg",
    imageAlt: "Calligraphy Pen",
    quantity: 1,
  },
  {
    id: 10,
    size: "Medium",
    color: "Normal",
    name: "Playing Cards ",
    quantityPrice: 20,
    price: 20,
    imageSrc: "/Cards.jpg",
    imageAlt: "Playing ",
    quantity: 1,
  },
  {
    id: 11,
    size: "Medium ",
    color: "Brown ",
    name: "Coffee Cup ",
    quantityPrice: 20,
    price: 20,
    imageSrc: "/coffee-cup.jpg",
    imageAlt: "Coffee Cup",
    quantity: 1,
  },
  {
    id: 12,
    size: "Large",
    color: "Blue",
    name: "Jeans Pant For Men  ",
    quantityPrice: 30,
    price: 30,
    imageSrc: "/blue-jeans.jpg",
    imageAlt: "Blue Jeans for men",
    quantity: 1,
  },
  {
    id: 13,
    size: "-- ",
    color: "White ",
    name: "Earphones ",
    quantityPrice: 30,
    price: 30,
    imageSrc: "/earphones.jpg",
    imageAlt: "Earphones",
    quantity: 1,
  },
  {
    id: 14,
    size: "-- ",
    color: "Black ",
    name: "Iphone ",
    quantityPrice: 300,
    price: 300,
    imageSrc: "/iphone.jpg",
    imageAlt: "",
    quantity: 1,
  },
  {
    id: 15,
    size: "Pro ",
    color: "White ",
    name: "MacBook ",
    quantityPrice: 350,
    price: 350,
    imageSrc: "/macbook.jpg",
    imageAlt: "Macbook",
    quantity: 1,
  },
  {
    id: 16,
    size: "Small ",
    color: "White ",
    name: " Footwear",
    quantityPrice: 15,
    price: 15,
    imageSrc: "/foot-wear.jpg",
    imageAlt: "Foot Wear",
    quantity: 1,
  },
  {
    id: 17,
    size: "500ml ",
    color: "--",
    name: "Red Wine ",
    quantityPrice: 120,
    price: 120,
    imageSrc: "/red-wine.jpg",
    imageAlt: "Red Wine",
    quantity: 1,
  },
  {
    id: 18,
    size: " Medium",
    color: "Brown ",
    name: " T-Shirt",
    quantityPrice: 35,
    price: 35,
    imageSrc: "/t-shirt.png",
    imageAlt: "T-shirt",
    quantity: 1,
  },
];
